stages:
    - build
pages:
    stage: build
    image:
    name: amp_pcmt/mkdocs-material
    entrypoint:
        - ""
    script:
        - mkdocs build
        - mv site public
    artifacts:
        paths:
            - public

